baseurl = "/"
languageCode = "en-us"
title = "Richard's Page"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3

[params]
    description = "A website built through Hugo and blogdown."
	profilePicture = "images/ralphie.jpg"
    footer = "[Github](https://github.com/richjand) | [LinkedIn](https://www.linkedin.com/in/richard-anderson-a9b445b2/) | [Twitter](https://www.twitter.com/richjand)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
